<?php


use PHPUnit\Framework\TestCase;

class PaymentTest extends  TestCase
{
    private $payment;

    protected function setUp() : void
    {
        $this->payment = new \App\Models\Payment("test", "123");
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public  function testPayment()
    {
        $this->assertEquals("test", $this->payment->getEmail());
    }
}