<?php

use App\Database;
use PHPUnit\Framework\TestCase;

class DatabaseTest extends  TestCase
{
    private $database;

    protected function setUp() : void
    {
        App\TestHelper::Print("ROOT:" . dirname(__FILE__));
        $this->database = Database::getInstance();
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public  function testDatabase()
    {
        $this->assertTrue(true);
    }
}